### ISSUE TITLE
/lib/ld-linux-aarch64.so.1: error

### ISSUE THREAD

**Issue by aka0kuro** [OpenVoiceOS/ovos-buildroot#117]
Hello, I am compiling for a raspberry pi 4 in ubuntu 20.04 and it gives me the following error, I hope you can help me. Thank you

`[ 30%] Built target kio_ftp_autogen
[ 30%] Automatic MOC for target ktrash5
[ 30%] Generating kcmtrash.json
/lib/ld-linux-aarch64.so.1: No such file or directory
[ 30%] Built target KF5KIOGui_autogen
make[5]: *** [src/ioslaves/trash/CMakeFiles/kcm_trash_autogen.dir/build.make:65: src/ioslaves/trash/kcmtrash.json] Error 255
make[4]: *** [CMakeFiles/Makefile2:1794: src/ioslaves/trash/CMakeFiles/kcm_trash_autogen.dir/all] Error 2
make[4]: *** Se espera a que terminen otras tareas....
Scanning dependencies of target kio_remote_autogen
[ 31%] Automatic MOC for target kio_trash
[ 32%] Automatic MOC for target kio_remote
[ 32%] Built target ktrash5_autogen
[ 32%] Built target kio_trash_autogen
[ 32%] Built target kio_remote_autogen
[ 32%] Built target pofiles-4a11423fae3027a0c86ccf02774a4242
make[3]: *** [Makefile:133: all] Error 2

`

**Comment by j1nx** [comment]
No longer needed.
