### ISSUE TITLE
Can't SSH

### ISSUE THREAD

**Issue by ghamauricio** [OpenVoiceOS/ovos-buildroot#119]
Hello all.

I think I'm having trouble with my screens (one might be too high a resolution - 4k, seems to be utterly unresponsive - and the other is just plain problematic - had problems with it kinda resetting and crashing the pi in the past), so I'm trying to SSH into the Pi with no sucess.

Tried mycroft:mycroft, pi:mycroft, pi:raspberry, mycroft:raspberry with no sucess.

What could be wrong?

**Comment by NeonDaniel** [comment]
Which image did you install? One from [openvoiceos.com](https://openvoiceos.com/) or one linked in the [Matrix chat](https://matrix.to/#/#openvoiceos-development:matrix.org)?

**Comment by j1nx** [comment]
The current user/passwd combo for this image is ovos/ovos
