### ISSUE TITLE
OCP plugins support

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-buildroot#126]
- bump ocp
- bump news skill
- include 
    https://github.com/OpenVoiceOS/ovos-ocp-files-plugin
    https://github.com/OpenVoiceOS/ovos-ocp-youtube-plugin
    https://github.com/OpenVoiceOS/ovos-ocp-m3u-plugin
    https://github.com/OpenVoiceOS/ovos-ocp-rss-plugin
    https://github.com/OpenVoiceOS/ovos-ocp-deezer-plugin
    https://github.com/OpenVoiceOS/ovos-ocp-bandcamp-plugin
    https://github.com/OpenVoiceOS/ovos-ocp-news-plugin

**Comment by j1nx** [comment]
What about the default shipped; https://github.com/OpenVoiceOS/skill-ovos-youtube-music

**Comment by JarbasAl** [comment]
no need, only news skill was updated to use the new news extractor as a speed optimization, the other skills dont need any changes. most plugins above already existed but hardcoded, only news plugin is new

**Comment by j1nx** [comment]
Fixed with the containarized system
