### ISSUE TITLE
Fedora uses `/usr/libexec/` not `/usr/lib/libexec`

### ISSUE THREAD

**Issue by Ramblurr** [OpenVoiceOS/ovos-buildroot#127]
(as discussed in matrix)

https://github.com/OpenVoiceOS/ovos-buildroot/blob/bfdc33ae1a32912f2630ea39de09ef159f07a3e5/buildroot-external/package/kf5-kconfig/kf5-kconfig.mk#L29

On my systemd (Fedora 37) this file is in `/usr/libexec/` not `/usr/lib/libexec`.  Maybe we could try both?

**Comment by j1nx** [comment]
Lol, just wanted to quickly create an issue such that I don't forget.

Great to have you onboard! You know the drill.

**Comment by denics** [comment]
What about using automake to generate the makefile?

**Comment by j1nx** [comment]
No longer needed / an issue
