### ISSUE TITLE
[BUG] WebSocket transport not available. Install simple-websocket for improved performance.

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-buildroot#136]
**OpenVoiceOS specifications (please complete the following information):**
 - Device: Mark2-Devkit
 - Image release: 20230117

**Describe the bug**
When launching the dashboard we get the message:
```
Mar 04 19:22:49 OpenVoiceOS-e383a2 python[1883]:  * Serving Flask app "app" (lazy loading)
Mar 04 19:22:49 OpenVoiceOS-e383a2 python[1883]:  * Environment: production
Mar 04 19:22:49 OpenVoiceOS-e383a2 python[1883]:    WARNING: This is a development server. Do not use it in a production deployment.
Mar 04 19:22:49 OpenVoiceOS-e383a2 python[1883]:    Use a production WSGI server instead.
Mar 04 19:22:49 OpenVoiceOS-e383a2 python[1883]:  * Debug mode: on
Mar 04 19:22:49 OpenVoiceOS-e383a2 python[1883]:  * Running on http://0.0.0.0:5005/ (Press CTRL+C to quit)
Mar 04 19:22:49 OpenVoiceOS-e383a2 python[1883]:  * Restarting with inotify reloader
Mar 04 19:22:50 OpenVoiceOS-e383a2 python[1894]: WebSocket transport not available. Install simple-websocket for improved performance.
```

**To Reproduce**
1. `systemctl --user enable ovos-dashboard@mycroft.service`
2. `systemctl --user start ovos-dashboard@mycroft.service`
3. `systemctl --user status ovos-dashboard@mycroft.service`

**Expected behavior**
I think simple-websocket should be installed in the buildroot image. Doing ``pip install simple-websocket`` solve the error

**Comment by j1nx** [comment]
Thanks for that. Will take care of includinig simple-websocket.

**Comment by j1nx** [comment]
Closing this one as at that point I indeed included the  simple-websocket python package.

However we are now using containers.
