### ISSUE TITLE
Bluetooth speaker

### ISSUE THREAD

**Issue by andlo** [OpenVoiceOS/ovos-buildroot#166]
**OpenVoiceOS specifications (please complete the following information):**
 - Device: Mark2
 - Image release: latest
 
**Describe the bug**
the device dosnt popup as a bluetooth speaker
(which also is described in the docs that it currently dosnt work)

**To Reproduce**
open phone and scan for buetooth devises

**Expected behavior**
Iexpected that he device showed up as a bluetooth speaker on my phone

**Additional context**
In the /etc/pulse/system.pa it will load the modules if they exists. My thaught were that maybe these mpodules isnt in the image.

![image](https://user-images.githubusercontent.com/3314671/232338780-de6460e2-f0dd-4339-bd26-1d65aa84166a.png)

**Comment by j1nx** [comment]
Closing this one as we now use Pipewire. However the Bluetooth speaker implementation has not yet been fully implemented.
