### ISSUE TITLE
[BUG] ovos-bus-client is missing and prevent PHAL from running

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-buildroot#170]
**OpenVoiceOS specifications (please complete the following information):**
 - Device: RPi4
 - Image release: OpenVoiceOS_rpi3_64-gui_dev-202301171328.img
 - Microphone type: SJ201
 - Sound output type: DevKit
 - Screen type: DevKit
 - Additional info: [e.g. Any information that might be relevant.]

**Describe the bug**
ovos-bus-client is missing and prevent PHAL from running

**Comment by j1nx** [comment]
Fixed
