### ISSUE TITLE
[BUG] missing userland files from raspberry

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-buildroot#171]
**OpenVoiceOS specifications (please complete the following information):**
 - Device: Mark2-Devkit
 - Image release: OpenVoiceOS_rpi3_64-gui_dev-202301171328.img
 

**Describe the bug**
Missing userland files from raspberry gives this error:

```
ovos_PHAL_plugin_brightness_control_rpi:discover:123 - ERROR - [Errno 2] No such file or directory: '/opt/vc/bin/vcgencmd'
```

**Comment by j1nx** [comment]
Fixed (although we do not need the vcgencmd command)
