### ISSUE TITLE
[Request] Missing Piper TTS

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-buildroot#174]
Apparently Piper is the new thing https://github.com/rhasspy/piper and it should be included as TTS server in images for RPi4.I think

**Comment by JarbasAl** [comment]
already exists https://github.com/OpenVoiceOS/ovos-tts-plugin-piper

**Comment by denics** [comment]
agree that it already exists, I am just making note of all packages that need to be included into the next buildroot

**Comment by lipschitzallee** [comment]
this one would be great:
https://github.com/cutiepi-io/cutiepi-doc

**Comment by j1nx** [comment]
Included and default now
