### ISSUE TITLE
[Request] Missing Mimic3 TTS server

### ISSUE THREAD

**Issue by denics** [OpenVoiceOS/ovos-buildroot#175]
in RPi4 image it make sense to include mimic3 TTS server for local execution

**Comment by JarbasAl** [comment]
that is already the default TTS in ovos https://github.com/OpenVoiceOS/ovos-tts-plugin-mimic3-server

**Comment by j1nx** [comment]
TTS default is now using the piper online servers with local mimic1 as fallback.
