### ISSUE TITLE
Can't download your img file

### ISSUE THREAD

**Issue by czadikem** [OpenVoiceOS/ovos-buildroot#34]
When I download your image file it says 0b can you give me another link please. the link I used was https://www.j1nx.nl/download/mycroftos-0-1-0-alpha8-rpi4-64bit/

Thanks

**Comment by czadikem** [comment]
Here 
![mycroftoserror](https://user-images.githubusercontent.com/35937408/88334583-3c59f580-ccef-11ea-9e1d-7d1efc9b0600.png)
is a picture of me using commandline to try and download the file

**Comment by j1nx** [comment]
And this direct link?
https://j1nx.stackstorage.com/s/dUnc2C50fEv73La3

**Comment by czadikem** [comment]
Sorry for the late reply.  But The link above is not working.  So I would
change your file storage to something like Google drive etc.

**Comment by j1nx** [comment]
https://drive.google.com/file/d/1So5knzMwUtrqnjUE2iJAgt5yS9nhJ1ME/view?usp=sharing

Give it a try.

**Comment by czadikem** [comment]
Thanks that works for me😄!
