### ISSUE TITLE
Debugging on boot

### ISSUE THREAD

**Issue by Montanadude** [OpenVoiceOS/ovos-buildroot#35]
Is there command to see the logs while booting? I'm asking as it seems when we don't hear
mycroft talking we have no way to troubleshoot to see if it is a wifi issue or a problem with
respeaker.  Tried doing Alt-F1, but no go.  Something like this would be really helpful.  Thanks!

**Comment by j1nx** [comment]
There is no linux cli available on the screen itself. As this Issue is rather old, closing it now. Assume it is fixed somewhere over time. Feel free to re-open if not.
