### ISSUE TITLE
Install fails when 1.1.1.1 is down

### ISSUE THREAD

**Issue by hieronymousch** [OpenVoiceOS/ovos-buildroot#37]
IP is hard coded in /etc/systemd/system/multi-user.target.wants/mycroft.service and was unreachable for me... so installation hung. Maybe ping a DNS name?

**Comment by j1nx** [comment]
Hi, them you have a rather old version running as the internet check has been removed a while ago.

Which RPI do you have? So i can give you a link to the latest download available.

**Comment by hieronymousch** [comment]
Pi 3B, I just downloaded the release on this page.. Thanks for your help!

**Comment by hieronymousch** [comment]
Found the download page via the forum, will try that version. (link: https://www.j1nx.nl/downloads/ )
thanks

**Comment by j1nx** [comment]
If you have an RPI4, you are beter of downloading this;
https://j1nx.stackstorage.com/s/LPPpy2VkyV8Vww4I
