### ISSUE TITLE
patch: hardcoded speech + bad enclosure assumptions

### ISSUE THREAD

**Issue by JarbasAl** [OpenVoiceOS/ovos-buildroot#47]
- removes hardcoded onboarding (speech + wifi + pairing message + mic muting....)
- moves readiness check to appropriate place

https://github.com/MycroftAI/mycroft-core/compare/dev...OpenVoiceOS:refactor/enclosure_assumptions

**Comment by ChanceNCounter** [comment]
Is the TODO on `enclosure.base.py:74` blocking?

**Comment by ChanceNCounter** [comment]
Hardcoded timeout on 133 may be objectionable.

**Comment by AIIX** [comment]
Testing the patch still reports the "mycroft.skills.trained" message on bus to early even on first boot

**Comment by ChanceNCounter** [comment]
Probably good to log (or at least print) status during that while loop, as it's in a core component and could cause Mycroft to (effectively) hang quietly.

**Comment by JarbasAl** [comment]
https://github.com/MycroftAI/mycroft-core/compare/dev...OpenVoiceOS:refactor/enclosure_assumptions

should account for pairing now before reporting ready

**Comment by JarbasAl** [comment]
> Hardcoded timeout on 133 may be objectionable.

that TODO comes from mycroft, its not blocking and is in general a safe assumption, anyway @j1nx can enforce that skills only boots after enclosure i think

**Comment by j1nx** [comment]
Not really sure about that, but will investigate.

edit: read that wrong. Indeed but depends on the systemd notify patch we have planned. For now indeed i can make the skills service only start after starting enclosure first.

**Comment by j1nx** [comment]
Systemd / Notifyd is implemented. Closing this one as the enclosure assumption patch is no longer valid with mycroft-lib.
