### ISSUE TITLE
Package: Gstreamer Plugins Bad

### ISSUE THREAD

**Issue by AIIX** [OpenVoiceOS/ovos-buildroot#49]
Gstreamer Plugins Bad seems to be missing on image and is required for hw accel playback and raspi camera via v4l2 interface

**Comment by j1nx** [comment]
Gstreamer Plugins Bad is added within OVOS. Camera is not yet working, but possibly related to hardware drivers.

Closing this one, in favor of a newly created Issue about it later on in time, when we get to it.
