### ISSUE TITLE
Build problems ahead of first alpha release

### ISSUE THREAD

**Issue by ChanceNCounter** [OpenVoiceOS/ovos-buildroot#59]
PLEASE NOTE: The OVOS dev team will not be in a position to debug build problems until after the alpha release. If the system won't build on your system, please be patient! An alpha image will come soon, after which we can begin looking at other people's computers.

Finding out why a program builds on one computer, but not another computer, is an absolute nightmare, unless the two computers are running the same version of the same operating system. It's time we can't afford to spend right now. Thanks for understanding.

**Comment by j1nx** [comment]
This has been fixed during the containerized system implementation. If things do not build following teh build steps, that is a bug and I would like to know about it within a new issue.

Closing this one as cmplete
