### ISSUE TITLE
almost-alpha  long running issues

### ISSUE THREAD

**Issue by Olzeke51** [OpenVoiceOS/ovos-buildroot#75]
Mk2-devkit on usb drive, network cable
seems there are long term (> 12 hrs ??) issues creeping in
1) the other day I put it to 'go to sleep' ["naptime" didn't work] but the next morning I had 'standby face'
no audio or mic connected (cept SJ)
2) just now attempted to do 2 or 3 [gui-menu] restarts and a stop - got no results
.    yesterday it would act appropriately - a long green acitivity pi-led, then 28-31 short leds, then blank & restart !
.
** - thot - maybe the midnight rollover ?? in the time
[mycroft-longterm.tar.gz](https://github.com/OpenVoiceOS/OpenVoiceOS/files/7006306/mycroft-longterm.tar.gz)

**Comment by j1nx** [comment]
should be fixed by now
