### ISSUE TITLE
almost-alpha 0816 - funky response from mycroft-say-to re:time request

### ISSUE THREAD

**Issue by Olzeke51** [OpenVoiceOS/ovos-buildroot#77]
flashed new image to usb / mark2-devkit - network cable
selene/Mycroft backend selected
mycroft-say-to what's the time       **got a prompt instead of time ???????
'''mycroft@OpenVoiceOS-e37cd7:~ $ pacmd set-default-sink 0
mycroft@OpenVoiceOS-e37cd7:~ $ mycroft-speak this is really cool stuff
mycroft@OpenVoiceOS-e37cd7:~ $ mycroft-say-to sing for me
mycroft@OpenVoiceOS-e37cd7:~ $ mycroft-say-to sing to me
mycroft@OpenVoiceOS-e37cd7:~ $ mycroft-say-to what's the time
> ^C
mycroft@OpenVoiceOS-e37cd7:~ $ mycroft-say-to what is the time
mycroft@OpenVoiceOS-e37cd7:~ $ mycroft-say-to what's the time
> ls
> help
> list
> exit
> bye
> ^C
mycroft@OpenVoiceOS-e37cd7:~ $ 
'''
**short time span ~40 minutes altogether

[mycroft-backend-fresh.tar.gz](https://github.com/OpenVoiceOS/OpenVoiceOS/files/7009959/mycroft-backend-fresh.tar.gz)

**Comment by Olzeke51** [comment]
this also happens to "what's the weather" vs 'what is the weather'
**
note : having trouble with usb-headset so I am using the CLI

**Comment by j1nx** [comment]
should be fixed, if not let me know
