### ISSUE TITLE
preAlpha-0828 - inconsistent audio out

### ISSUE THREAD

**Issue by Olzeke51** [OpenVoiceOS/ovos-buildroot#85]
Mark2-devkit/SJ board ; usb flash; network cable
fresh image - boot up -ncpamixer only has 'dummy' input
   ssh/cli 'shutdown now -r'  : ncpamixer still only dummy  -- plug in usb-headset  -now pactl reports usb-mic as source
   but pactl sink is only 'dummy'
  ssh/cli  set volume to 40%
Restart from menu (was real fast - sometimes 31 green-media(pi) blinks)
   SJ spkr LOUDLY reports it is now ready
**
can't seem to get the headset audio
pwr cycle - no SJ speaker/ headset
pactl list sinks = 'dummy' only !!!
**
[ovos-2028-audio-iss.tar.gz](https://github.com/OpenVoiceOS/OpenVoiceOS/files/7079944/ovos-2028-audio-iss.tar.gz)

**Comment by ChanceNCounter** [comment]
Did this get sorted in chat?

**Comment by Olzeke51** [comment]
no, not as of the 10-06 ;  sometimes it responds to usb headset , sometime
not,
can't remember the last time I had mycroft speakers make sound !!
thanks for asking, Gary

**Comment by j1nx** [comment]
Should be fixed by now. If not, please let me know
