### ISSUE TITLE
Trying to build on Fedora 34 (35 now)

### ISSUE THREAD

**Issue by brianread108** [OpenVoiceOS/ovos-buildroot#90]
Found quite a few missing deps (perl and others). 
However Build fails with:

`/home/brianr/Data/brianr/OVOS/OpenVoiceOS/buildroot/output/build/qt5base-5.15.2/src/corelib/text/qbytearraymatcher.h:103:38: error: ‘numeric_limits’ is not a member of ‘std’
  103 |         const auto uchar_max = (std::numeric_limits<uchar>::max)();
      |                                      ^~~~~~~~~~~~~~
/home/brianr/Data/brianr/OVOS/OpenVoiceOS/buildroot/output/build/qt5base-5.15.2/src/corelib/text/qbytearraymatcher.h:103:58: error: expected primary-expression before ‘>’ token
  103 |         const auto uchar_max = (std::numeric_limits<uchar>::max)();
      |                                                          ^
/home/brianr/Data/brianr/OVOS/OpenVoiceOS/buildroot/output/build/qt5base-5.15.2/src/corelib/text/qbytearraymatcher.h:103:61: error: ‘::max’ has not been declared; did you mean ‘std::max’?
  103 |         const auto uchar_max = (std::numeric_limits<uchar>::max)();
      |                                                             ^~~
      |                                                             std::max

Any ideas?

**Comment by j1nx** [comment]
Okidokie, am at the same error as we speak.

Had to go for a fresh QT compile run because of the virtual keyboard work. Threw away all QT5 related build packages and re-compiling them and it errored out with that exact error.

So in short; Looking into it.

**Comment by j1nx** [comment]
Should be fixed now.

**Comment by brianread108** [comment]
Thanks, I am now on Fedora 35, and will have a go when I get time. I will report back.

**Comment by j1nx** [comment]
Hang on for a little bit longer. Going through a fresh compile showed some other quircks here and there that i also addressing when they pop up.
